name: Build and Upload Tauri App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build Tauri App
        run: |
          tauri build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tauri-artifacts
          path: target

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: tauri-artifacts

      - name: Set up SSH keys
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          eval $(ssh-agent -s)
          ssh-add ssh_key

      - name: Upload Artifacts to Server
        run: scp -i ssh_key -r target/ user@your_server_ip:/path/to/destination

      - name: SSH into Server
        run: ssh -i ssh_key user@your_server_ip 'cd /path/to/destination && ./deploy-script.sh'
